# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)
development:
  adapter: mysql
  host: localhost
  database: trr_development
  username: root
  password:

test:
  adapter: mysql
  host: localhost
  database: trr_test
  username: root
  password:













