# The api key, secret key, and canvas page name are required to get started
# Tunnel configuration is only needed if you are going to use the facebooker:tunnel Rake tasks
# Your callback url in Facebook should be set to http://public_host:public_port
# To develop for the new profile design, add the following key..
# api: new
# remove the key or set it to anything else to use the old facebook design.
# This should only be necessary until the final version of the new profile is released.

development:
  api_key: 31a6653fd31a253e9ef77e4c2e2548eb
  secret_key: 2a02c155c90ccab00ad38589367992b5
  canvas_page_name: mylootlo
  callback_url: http://lootlo.heroku.com/fb/connect/
  pretty_errors: true
  set_asset_host_to_callback_url: false

test:
  api_key: 31a6653fd31a253e9ef77e4c2e2548eb
  secret_key: 2a02c155c90ccab00ad38589367992b5
  canvas_page_name: mylootlo
  callback_url: http://lootlo.heroku.com/fb/connect/

production:
  api_key: 31a6653fd31a253e9ef77e4c2e2548eb 
  secret_key: 2a02c155c90ccab00ad38589367992b5 
  canvas_page_name: mylootlo
  callback_url: http://lootlo.heroku.com/fb/connect/  
